"""Add fee to design table

Revision ID: 0007
Revises: 0006
Create Date: 2019-05-30 09:58:01.563331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('design', sa.Column('fee', sa.Numeric(), nullable=True))
    op.execute("UPDATE design SET fee=2.00")
    op.alter_column('design', 'fee', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design', 'fee')
    # ### end Alembic commands ###
