"""Add listable column to design table

Revision ID: 0009
Revises: 0008
Create Date: 2019-06-26 10:11:12.224125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design', sa.Column('listable', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design', 'listable')
    # ### end Alembic commands ###
