"""Hash all deviceTokens for safety.

Revision ID: 0012
Revises: 0011
Create Date: 2019-08-14 14:21:55.570300

"""
from alembic import op
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base
import hashlib
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None

Base = declarative_base()


# This version of the Device table contains only the columns needed for
# this migration. See:
# https://stackoverflow.com/questions/24612395/how-do-i-execute-inserts-and-updates-in-an-alembic-upgrade-script
class Device(Base):
    __tablename__ = 'device'
    id = sa.Column(sa.String, nullable=False, primary_key=True)
    deviceToken = sa.Column(sa.String)
    token_sha256 = sa.Column(sa.String)


def upgrade():
    bind = op.get_bind()
    dbsession = orm.Session(bind=bind)

    op.add_column('device', sa.Column('token_sha256', sa.String()))

    for device in dbsession.query(Device).all():
        if len(device.deviceToken) < 2:
            raise ValueError(
                "Device %s: length of deviceToken is too short: %s" %
                (device.id, repr(device.deviceToken)))
        digest = hashlib.sha256(device.deviceToken.encode('utf-8')).hexdigest()
        device.token_sha256 = digest

    print("deviceTokens hashed; sending...")
    dbsession.commit()
    print("sent hashes.")

    op.alter_column('device', 'token_sha256', nullable=False)
    op.create_index(op.f('ix_device_token_sha256'), 'device', ['token_sha256'], unique=True)
    op.drop_index('ix_device_deviceToken', table_name='device')
    op.drop_column('device', 'deviceToken')


def downgrade():
    raise ValueError(
        "deviceToken hashing is irreversible by design, "
        "so automated downgrades of this revision are disabled.")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('deviceToken', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_device_deviceToken', 'device', ['deviceToken'], unique=True)
    op.drop_index(op.f('ix_device_token_sha256'), table_name='device')
    op.drop_column('device', 'token_sha256')
    # ### end Alembic commands ###
