"""Added Verify Column to CardRequest

Revision ID: 0013_add_verify
Revises: 0012
Create Date: 2019-09-30 14:55:48.774548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013_add_verify'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_request', sa.Column('verified', sa.Unicode(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_request', 'verified')
    # ### end Alembic commands ###
