"""add invalid_count

Revision ID: 0014
Revises: 0013_add_verify
Create Date: 2019-12-18 09:46:52.546126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0014'
down_revision = '0013_add_verify'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('invalid_count', sa.Unicode(), server_default='', nullable=False))
    op.add_column('customer', sa.Column('invalid_date', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'invalid_count')
    op.drop_column('customer', 'invalid_date')
    # ### end Alembic commands ###
