"""add Index

Revision ID: 0019
Revises: 0018
Create Date: 2020-04-20 14:47:23.332290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notification', 'notification', ['transfer_id', 'customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification', table_name='notification')
    # ### end Alembic commands ###
